module.exports = {
  someSidebar: {
    Designing: ["designing/design-kits"],
    Developing: [
      "developing/installing-from-npm",
      "developing/installing-from-dist",
      "developing/updating",
      "developing/browser-support",
      "developing/react",
      "developing/page-template",
      "developing/typography",
      "developing/colours",
      {
        type: "link",
        label: "Sass reference",
        href: "pathname:///sassdoc/index.html",
      },
    ],
    Components: [
      "components/accordion",
      "components/announcement",
      "components/back-link",
      "components/back-to-top",
      "components/breadcrumbs",
      "components/button",
      "components/contacts-block",
      "components/conversation",
      "components/collapsible",
      "components/character-count",
      "components/checkboxes",
      "components/cookie-banner",
      "components/date-input",
      "components/details",
      "components/dialog",
      "components/error-message",
      "components/error-summary",
      "components/fieldset",
      "components/file-upload",
      "components/header",
      "components/hint",
      "components/input",
      "components/inset-text",
      "components/label",
      "components/page-announcement",
      "components/pagination",
      "components/panel",
      "components/phase-banner",
      "components/radios",
      "components/search-box",
      "components/select",
      "components/simple-pagination",
      "components/skip-link",
      "components/summary-list",
      "components/stat",
      "components/table",
      "components/tag",
      "components/tabs",
      "components/textarea",
      "components/timeline",
      "components/tip",
      "components/warning-text",
    ],
    Patterns: ["patterns/sign-in", "patterns/navigation"],
    "Starter kits": ["tutorials/prototype", "tutorials/production"],
    "Data visualisation": [
      "data-visualisation/getting-started"
    ],
    Contributing: [
      "contributing/introduction",
      "contributing/coding-standards",
    ],
  },
};
