module.exports = {
  someSidebar: {
    "Get started": [
      "docs/getting-started",
      "docs/using-it-in-prototypes",
      "docs/using-it-in-production",
      "docs/browser-support",
      "docs/contributing",
    ],
    Components: [
      "lbh/components/lbh-accordion/README",
      // "lbh/components/lbh-announcement/README",
      // "lbh/components/lbh-back-link/README",
      // "lbh/components/lbh-back-to-top/README",
      // "lbh/components/lbh-breadcrumbs/README",
      // "lbh/components/lbh-button/README",
      // "lbh/components/lbh-character-count/README",
      // "lbh/components/lbh-checkboxes/README",
      // "lbh/components/lbh-contact-block/README",
      // "lbh/components/lbh-cookie-banner/README",
      // "lbh/components/lbh-date-input/README",
      // "lbh/components/lbh-details/README",
      // "lbh/components/lbh-error-message/README",
      // "lbh/components/lbh-error-summary/README",
      // "lbh/components/lbh-fieldset/README",
      // "lbh/components/lbh-header/README",
      // "lbh/components/lbh-hint/README",
      // "lbh/components/lbh-input/README",
      // "lbh/components/lbh-inset-text/README",
      // "lbh/components/lbh-label/README",
      // "lbh/components/lbh-page-announcement/README",
      // "lbh/components/lbh-panel/README",
      // "lbh/components/lbh-phase-banner/README",
      // "lbh/components/lbh-radios/README",
      // "lbh/components/lbh-select/README",
      // "lbh/components/lbh-skip-link/README",
      // "lbh/components/lbh-summary-list/README",
      // "lbh/components/lbh-tabs/README",
      // "lbh/components/lbh-tag/README",
      // "lbh/components/lbh-textarea/README",
      // "lbh/components/lbh-warning-text/README",
    ],
  },
};
