name: Publish documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - name: Install modules
        run: npm ci
      - name: Test documentation build
        run: npm run build:docs
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - uses: actions/checkout@v4
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.RELEASE_PLEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_PRIVATE_KEY }}
          permission-contents: write
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - name: Install modules
        run: npm ci
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_USER: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          npm run build:sassdoc
          npx docusaurus deploy
